project_id = "glmhttliyzvwzqnqznfx"

[functions.send-order-notification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.resend-order-email]
verify_jwt = false

[functions.validate-gift-card]
verify_jwt = false

[functions.process-gift-card-order]
verify_jwt = false
